"""Bake glyph coverage and the supplied logo for the CPU framebuffer.
No font files or image-generation services are required at runtime.
"""
from pathlib import Path
from PIL import Image,ImageFont,ImageDraw
root=Path(__file__).resolve().parents[1]
coverage=bytearray();tables=[]
for size,bold in [(16,False),(20,False),(28,True),(44,True)]:
 font=ImageFont.truetype('C:/Windows/Fonts/seguisb.ttf' if bold else 'C:/Windows/Fonts/segoeui.ttf',size)
 ascent=font.getmetrics()[0];glyphs=[]
 for code in range(32,256):
  ch=chr(code);x0,y0,x1,y1=font.getbbox(ch,anchor='ls');w=max(0,x1-x0);h=max(0,y1-y0)
  glyphs.append((len(coverage),w,h,x0,y0+ascent,round(font.getlength(ch))))
  if w and h:
   image=Image.new('L',(w,h));ImageDraw.Draw(image).text((-x0,-y0),ch,font=font,fill=255,anchor='ls');coverage.extend(image.tobytes())
 tables.append(glyphs)
logo=Image.open(root/'assets/icon0.png').convert('RGB').resize((88,88),Image.Resampling.LANCZOS)
lines=['/* Generated by tools/make_ui_assets.py; glyph bitmaps, not a font file. */',
 'typedef struct { unsigned int offset; short w,h,x,y,advance; } UiGlyph;',
 'static const UiGlyph ui_glyphs[4][224]={']
for table in tables:lines.append('{'+','.join('{'+','.join(map(str,g))+'}' for g in table)+'},')
lines.extend(['};','static const unsigned char ui_coverage[]={'])
for i in range(0,len(coverage),48):lines.append(','.join(map(str,coverage[i:i+48]))+',')
lines.extend(['};','static const unsigned int ui_logo[]={'])
pixels=[0xff000000|(r<<16)|(g<<8)|b for r,g,b in logo.getdata()]
for i in range(0,len(pixels),16):lines.append(','.join(hex(x) for x in pixels[i:i+16])+',')
lines.append('};')
(root/'src/ui_assets.h').write_text('\n'.join(lines)+'\n')
print('Baked',len(coverage),'glyph alpha bytes and',len(pixels),'logo pixels')
